server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: totoro

mybatis:
  # XML 매퍼 파일 위치 지정
  mapper-locations: classpath:mapper/*.xml
  # DTO/Model 패키지 별칭(Type Alias) 설정
  type-aliases-package: com.example.kanban.dto
  # 카멜케이스 자동 매핑 (db_column -> dbColumn)
  configuration:
    map-underscore-to-camel-case: true